const stepContact = {
  fr: {
    nameLabel: "Votre nom ou entreprise",
    namePlaceholder: "Jean Dupont / Acme SAS",
    emailLabel: "Votre email",
    emailPlaceholder: "vous@exemple.fr",
    phoneLabel: "Votre téléphone",
    phonePlaceholder: "+33 6 00 00 00 00",
    submit: "Envoyer ma demande →",
  },
  en: {
    nameLabel: "Your name or company",
    namePlaceholder: "Jane Smith / Acme Ltd",
    emailLabel: "Your email",
    emailPlaceholder: "you@example.com",
    phoneLabel: "Your phone number",
    phonePlaceholder: "+33 6 00 00 00 00",
    submit: "Send my request →",
  },
}

export const contactFormTranslations = {
  fr: {
    site: {
      title: "Décrivez-moi votre projet",
      intro: "Deux questions et vos coordonnées, je vous recontacte rapidement pour discuter de votre projet et vous envoyer un devis.",
      stepActivity: { question: "Quelle est votre activité ?" },
      stepNeeds: {
        question: "De quoi avez-vous besoin ?",
        hint: "Sélectionnez tout ce qui vous correspond.",
      },
      stepContact: stepContact.fr,
      success: "Merci ! J'ai bien reçu votre demande et je vous recontacte rapidement.",
      activities: [
        {
          id: "restaurant",
          label: "Restaurant / Bar / Café",
          needs: [
            "Carte / menu modifiable en ligne (plats, boissons, prix)",
            "Système de réservation en ligne",
            "Menu compatible QR code",
            "Galerie photos de mes plats et de mon établissement",
            "Site en plusieurs langues",
            "Formulaire de contact",
            "Carte Google Maps intégrée",
            "Mise en avant des événements et soirées spéciales",
          ],
        },
        {
          id: "commerce",
          label: "Commerce / Boutique",
          needs: [
            "Boutique en ligne",
            "Paiement en ligne (carte, PayPal...)",
            "Catalogue produits avec photos et descriptions",
            "Gestion des stocks",
            "Click & collect",
            "Bons de réduction et codes promo",
            "Avis clients",
            "Formulaire de contact",
            "Site en plusieurs langues",
            "Carte Google Maps intégrée",
          ],
        },
        {
          id: "artisan",
          label: "Artisan / Prestataire de service",
          needs: [
            "Galerie de mes réalisations",
            "Demande de devis en ligne",
            "Formulaire de contact",
            "Présentation de mes services et tarifs",
            "Zone d'intervention sur carte",
            "Avis et témoignages clients",
            "Prise de rendez-vous en ligne",
            "Carte Google Maps intégrée",
            "Blog ou actualités",
          ],
        },
        {
          id: "artiste",
          label: "Artiste / Créatif",
          needs: [
            "Portfolio de mes travaux",
            "Galerie photos ou vidéos",
            "Vente de mes créations en ligne",
            "Agenda de mes événements et expositions",
            "Prise de contact pour des commandes",
            "Lecteur audio ou vidéo intégré",
            "Lien vers mes réseaux sociaux",
            "Site en plusieurs langues",
            "Blog ou journal créatif",
          ],
        },
        {
          id: "startup",
          label: "Startup / Entreprise",
          needs: [
            "Présentation de mon produit ou service",
            "Page équipe",
            "Blog ou ressources",
            "Formulaire de contact ou de démonstration",
            "Intégration CRM ou outils tiers",
            "Espace client ou portail",
            "Paiement ou abonnement en ligne",
            "Site en plusieurs langues",
            "Tableau de bord ou dashboard",
            "Témoignages et études de cas",
          ],
        },
        {
          id: "sante",
          label: "Professionnel de santé",
          needs: [
            "Prise de rendez-vous en ligne",
            "Présentation de ma pratique et de mes spécialités",
            "Formulaire de contact sécurisé",
            "Informations pratiques (horaires, adresse, accès)",
            "Carte Google Maps intégrée",
            "Blog ou articles de conseil",
            "Téléchargement de documents (ordonnances, formulaires...)",
            "Site en plusieurs langues",
          ],
        },
        {
          id: "liberal",
          label: "Professionnel libéral",
          needs: [
            "Présentation de mes services et expertises",
            "Prise de rendez-vous ou demande de consultation",
            "Formulaire de contact",
            "Téléchargement de documents",
            "Blog ou publications",
            "Témoignages clients",
            "Carte Google Maps intégrée",
            "Site en plusieurs langues",
          ],
        },
        {
          id: "association",
          label: "Association",
          needs: [
            "Présentation de l'association et de ses missions",
            "Agenda des événements",
            "Formulaire d'adhésion en ligne",
            "Don en ligne",
            "Blog ou actualités",
            "Galerie photos",
            "Formulaire de contact",
            "Espace membres",
            "Site en plusieurs langues",
          ],
        },
        {
          id: "autre",
          label: "Autre",
          needs: [
            "Présentation de mon activité",
            "Formulaire de contact",
            "Galerie photos ou portfolio",
            "Blog ou actualités",
            "Prise de rendez-vous en ligne",
            "Boutique ou vente en ligne",
            "Paiement en ligne",
            "Carte Google Maps intégrée",
            "Site en plusieurs langues",
          ],
        },
      ],
    },

    app: {
      title: "Décrivez-moi votre projet",
      intro: "Quelques questions pour cerner votre besoin, je vous recontacte rapidement avec une approche et un devis sur mesure.",
      stepActivity: { question: "Quel type d'application ?" },
      stepNeeds: {
        question: "Quelles fonctionnalités vous faut-il ?",
        hint: "Sélectionnez tout ce qui vous correspond.",
      },
      stepContact: stepContact.fr,
      success: "Merci ! J'ai bien reçu votre demande et je vous recontacte rapidement.",
      activities: [
        {
          id: "backoffice",
          label: "Outil interne / Back-office",
          needs: [
            "Gestion des utilisateurs et des permissions",
            "Tableau de bord et indicateurs clés (KPIs)",
            "Import / export de données (CSV, Excel...)",
            "Formulaires et workflows d'approbation",
            "Notifications et alertes",
            "Historique et journal d'activité",
            "Intégration avec des outils existants (CRM, ERP...)",
            "Recherche et filtres avancés",
          ],
        },
        {
          id: "espace-client",
          label: "Espace client / Portail",
          needs: [
            "Authentification (connexion / création de compte)",
            "Suivi de commandes ou de dossiers",
            "Documents téléchargeables",
            "Messagerie ou chat",
            "Paiement en ligne",
            "Notifications par email",
          ],
        },
        {
          id: "reservation",
          label: "Application de réservation / Planning",
          needs: [
            "Calendrier interactif",
            "Gestion des disponibilités",
            "Confirmation par email",
            "Rappels automatiques",
            "Paiement à la réservation",
            "Gestion multi-utilisateurs",
          ],
        },
        {
          id: "dashboard",
          label: "Dashboard / Reporting",
          needs: [
            "Visualisation de données (graphiques, tableaux)",
            "Connexion à des sources de données (API, BDD...)",
            "Filtres et périodes personnalisables",
            "Export PDF ou Excel",
            "Alertes et seuils",
            "Accès multi-utilisateurs avec rôles",
            "Mise à jour en temps réel",
          ],
        },
        {
          id: "elearning",
          label: "E-learning / Formation",
          needs: [
            "Gestion des cours et modules",
            "Lecteur vidéo intégré",
            "Suivi de la progression des apprenants",
            "Quiz et évaluations",
            "Certificats de complétion",
            "Espace formateur / administrateur",
            "Paiement et accès aux contenus",
            "Forum ou espace d'échange",
          ],
        },
        {
          id: "pwa",
          label: "Application mobile (PWA)",
          needs: [
            "Installation sur l'écran d'accueil",
            "Mode hors ligne",
            "Notifications push",
            "Géolocalisation",
            "Accès à la caméra ou aux fichiers",
            "Synchronisation en temps réel",
            "Interface optimisée mobile",
          ],
        },
        {
          id: "autre",
          label: "Autre",
          needs: [
            "Authentification utilisateur",
            "Base de données et gestion des données",
            "Interface d'administration",
            "Notifications",
            "Intégrations tierces",
            "Paiement en ligne",
            "Temps réel (chat, live updates...)",
            "Multilingue",
          ],
        },
      ],
    },
  },

  en: {
    site: {
      title: "Tell me about your project",
      intro: "Two questions and your contact details, I'll get back to you shortly to discuss your project and send you a quote.",
      stepActivity: { question: "What is your activity?" },
      stepNeeds: {
        question: "What do you need?",
        hint: "Select everything that applies to you.",
      },
      stepContact: stepContact.en,
      success: "Thank you! I've received your request and will get back to you shortly.",
      activities: [
        {
          id: "restaurant",
          label: "Restaurant / Bar / Café",
          needs: [
            "Menu / drinks list editable online (dishes, drinks, prices)",
            "Online reservation system",
            "QR code compatible menu",
            "Photo gallery of my dishes and venue",
            "Multilingual website",
            "Contact form",
            "Integrated Google Maps",
            "Highlight events and special evenings",
          ],
        },
        {
          id: "commerce",
          label: "Shop / Retail",
          needs: [
            "Online shop",
            "Online payments (card, PayPal...)",
            "Product catalogue with photos and descriptions",
            "Stock management",
            "Click & collect",
            "Discount codes and promotions",
            "Customer reviews",
            "Contact form",
            "Multilingual website",
            "Integrated Google Maps",
          ],
        },
        {
          id: "artisan",
          label: "Tradesperson / Service provider",
          needs: [
            "Gallery of my work",
            "Online quote request",
            "Contact form",
            "Presentation of my services and rates",
            "Service area map",
            "Customer reviews and testimonials",
            "Online appointment booking",
            "Integrated Google Maps",
            "Blog or news",
          ],
        },
        {
          id: "artiste",
          label: "Artist / Creative",
          needs: [
            "Portfolio of my work",
            "Photo or video gallery",
            "Sell my creations online",
            "Events and exhibitions calendar",
            "Contact for commissions",
            "Integrated audio or video player",
            "Links to my social media",
            "Multilingual website",
            "Blog or creative journal",
          ],
        },
        {
          id: "startup",
          label: "Startup / Business",
          needs: [
            "Presentation of my product or service",
            "Team page",
            "Blog or resources",
            "Contact or demo request form",
            "CRM or third-party tool integration",
            "Client portal or member area",
            "Online payment or subscription",
            "Multilingual website",
            "Dashboard",
            "Testimonials and case studies",
          ],
        },
        {
          id: "sante",
          label: "Healthcare professional",
          needs: [
            "Online appointment booking",
            "Presentation of my practice and specialities",
            "Secure contact form",
            "Practical information (hours, address, access)",
            "Integrated Google Maps",
            "Blog or advice articles",
            "Document downloads (forms, prescriptions...)",
            "Multilingual website",
          ],
        },
        {
          id: "liberal",
          label: "Independent professional",
          needs: [
            "Presentation of my services and expertise",
            "Appointment or consultation request",
            "Contact form",
            "Document downloads",
            "Blog or publications",
            "Client testimonials",
            "Integrated Google Maps",
            "Multilingual website",
          ],
        },
        {
          id: "association",
          label: "Non-profit / Association",
          needs: [
            "Presentation of the association and its missions",
            "Events calendar",
            "Online membership form",
            "Online donations",
            "Blog or news",
            "Photo gallery",
            "Contact form",
            "Members area",
            "Multilingual website",
          ],
        },
        {
          id: "autre",
          label: "Other",
          needs: [
            "Presentation of my activity",
            "Contact form",
            "Photo gallery or portfolio",
            "Blog or news",
            "Online appointment booking",
            "Shop or online sales",
            "Online payments",
            "Integrated Google Maps",
            "Multilingual website",
          ],
        },
      ],
    },

    app: {
      title: "Tell me about your project",
      intro: "A few questions to understand your needs, I'll get back to you with a tailored approach and quote.",
      stepActivity: { question: "What type of application?" },
      stepNeeds: {
        question: "What features do you need?",
        hint: "Select everything that applies to you.",
      },
      stepContact: stepContact.en,
      success: "Thank you! I've received your request and will get back to you shortly.",
      activities: [
        {
          id: "espace-client",
          label: "Client portal",
          needs: [
            "Authentication (login / account creation)",
            "Order or file tracking",
            "Downloadable documents",
            "Messaging or chat",
            "Online payments",
            "Email notifications",
          ],
        },
        {
          id: "reservation",
          label: "Booking / Scheduling app",
          needs: [
            "Interactive calendar",
            "Availability management",
            "Email confirmation",
            "Automatic reminders",
            "Payment at booking",
            "Multi-user management",
          ],
        },
        {
          id: "dashboard",
          label: "Dashboard / Reporting",
          needs: [
            "Data visualisation (charts, tables)",
            "Connect to data sources (API, database...)",
            "Customisable filters and date ranges",
            "PDF or Excel export",
            "Alerts and thresholds",
            "Multi-user access with roles",
            "Real-time updates",
          ],
        },
        {
          id: "elearning",
          label: "E-learning / Training",
          needs: [
            "Course and module management",
            "Integrated video player",
            "Learner progress tracking",
            "Quizzes and assessments",
            "Completion certificates",
            "Instructor / admin space",
            "Payment and content access",
            "Forum or discussion space",
          ],
        },
        {
          id: "pwa",
          label: "Mobile app (PWA)",
          needs: [
            "Add to home screen",
            "Offline mode",
            "Push notifications",
            "Geolocation",
            "Camera or file access",
            "Real-time sync",
            "Mobile-optimised interface",
          ],
        },
        {
          id: "autre",
          label: "Other",
          needs: [
            "User authentication",
            "Database and data management",
            "Admin interface",
            "Notifications",
            "Third-party integrations",
            "Online payments",
            "Real-time (chat, live updates...)",
            "Multilingual",
          ],
        },
      ],
    },
  },
}